import { Request, Response } from "express"; import { ModerationScanStatus } from "@prisma/client"; import { z } from "zod"; import { getErrorStatus } from "../../common/errors/app-error"; import { sendError, sendSuccess } from "../../common/utils/response"; import { InsightsService } from "./insights.service";
const eventSchema=z.object({anonymousId:z.string().min(8).max(200).optional(),sessionId:z.string().max(200).optional(),eventName:z.string().regex(/^[a-z][a-z0-9_.-]{1,99}$/),source:z.string().min(1).max(50),entityType:z.string().max(100).optional(),entityId:z.string().max(200).optional(),properties:z.record(z.unknown()).default({}),dedupeKey:z.string().max(200).optional(),occurredAt:z.coerce.date()}).strict();
const resultSchema=z.object({provider:z.string().min(1).max(100),modelName:z.string().min(1).max(200),modelVersion:z.string().max(100).optional(),promptVersion:z.string().min(1).max(100),classifications:z.array(z.unknown()).max(100),scores:z.record(z.number().min(0).max(1)),recommendedAction:z.string().min(1).max(100),latencyMs:z.number().int().nonnegative().optional(),inputTokens:z.number().int().nonnegative().optional(),outputTokens:z.number().int().nonnegative().optional()}).strict();
export class InsightsController{
 static async track(req:Request,res:Response){const p=eventSchema.safeParse(req.body);if(!p.success)return sendError(res,p.error.errors[0].message,400);try{return sendSuccess(res,await InsightsService.track({...p.data,userId:req.user?.id}),"Đã ghi nhận event",201);}catch(e){return sendError(res,e,getErrorStatus(e));}}
 static async scans(req:Request,res:Response){const s=typeof req.query.status==="string"&&Object.values(ModerationScanStatus).includes(req.query.status as ModerationScanStatus)?req.query.status as ModerationScanStatus:undefined;try{return sendSuccess(res,await InsightsService.listScans(s,Number(req.query.limit)||50));}catch(e){return sendError(res,e,getErrorStatus(e));}}
 static async result(req:Request,res:Response){const p=resultSchema.safeParse(req.body);if(!p.success)return sendError(res,p.error.errors[0].message,400);try{return sendSuccess(res,await InsightsService.recordModerationResult(req.params.scanId,p.data));}catch(e){return sendError(res,e,getErrorStatus(e));}}
 static async aggregate(req:Request,res:Response){const date=new Date(`${req.body?.date}T00:00:00.000Z`);if(Number.isNaN(date.getTime()))return sendError(res,"Ngày không hợp lệ",400);try{return sendSuccess(res,await InsightsService.aggregateDaily(date));}catch(e){return sendError(res,e,getErrorStatus(e));}}
}
