ALTER TABLE "Profile"
ADD COLUMN "aboutMe" TEXT,
ADD COLUMN "personalityType" TEXT,
ADD COLUMN "lifestyle" TEXT,
ADD COLUMN "hobbies" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "skills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "favoriteColors" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "socialLinks" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "galleryMediaIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
